info:
  contact: {}
paths:
  /total_time/count:
    get:
      description: Получение всех интервалов
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: list
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get total count time
      tags:
      - Count total time
swagger: "2.0"
